apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeathrix.fullname" . }}-operator
  labels:
    {{- include "kubeathrix.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.operator }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.deploymentStrategy.maxSurge }}
      maxUnavailable: {{ .Values.deploymentStrategy.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "kubeathrix.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: operator
  template:
    metadata:
      {{- if .Values.rollout.restartToken }}
      annotations:
        kubeathrix.io/restart-token: {{ .Values.rollout.restartToken | quote }}
      {{- end }}
      labels:
        {{- include "kubeathrix.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: operator
    spec:
      serviceAccountName: {{ include "kubeathrix.fullname" . }}-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: manager
          image: {{ if .Values.image.operator.digest }}"{{ .Values.image.operator.repository }}@{{ .Values.image.operator.digest }}"{{ else }}"{{ .Values.image.operator.repository }}:{{ .Values.image.operator.tag }}"{{ end }}
          imagePullPolicy: {{ .Values.image.operator.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          args:
            - --health-probe-bind-address=:8081
            - --leader-elect
          env:
            - name: KUBEATHRIX_MUTATION_ENABLED
              value: {{ .Values.remediation.mutationEnabled | quote }}
          ports:
            - name: metrics
              containerPort: 8080
            - name: probes
              containerPort: 8081
          readinessProbe:
            httpGet:
              path: /readyz
              port: probes
          livenessProbe:
            httpGet:
              path: /healthz
              port: probes
          resources:
            {{- toYaml .Values.resources.operator | nindent 12 }}
