apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeathrix.fullname" . }}-console
  labels:
    {{- include "kubeathrix.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.console }}
  selector:
    matchLabels:
      {{- include "kubeathrix.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: console
  template:
    metadata:
      labels:
        {{- include "kubeathrix.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: console
    spec:
      serviceAccountName: {{ include "kubeathrix.fullname" . }}-console
      containers:
        - name: console
          image: "{{ .Values.image.console.repository }}:{{ .Values.image.console.tag }}"
          imagePullPolicy: {{ .Values.image.console.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources.console | nindent 12 }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "kubeathrix.fullname" . }}-console-nginx
