{{- if and (not .Values.postgres.external) (not .Values.postgres.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeathrix.postgresSecretName" . }}
  labels:
    {{- include "kubeathrix.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.postgres.passwordKey }}: {{ randAlphaNum 32 | quote }}
{{- end }}
