apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeathrix.fullname" . }}-api
  labels:
    {{- include "kubeathrix.labels" . | nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeathrix.fullname" . }}-operator
  labels:
    {{- include "kubeathrix.labels" . | nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeathrix.fullname" . }}-console
  labels:
    {{- include "kubeathrix.labels" . | nindent 4 }}
automountServiceAccountToken: false
